---
title: "ongoing"
author: "Carlos Granell"
date: "15/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, message = FALSE, warning = FALSE)
```


```{r setup}
library(flexdashboard)
library(here)
library(kableExtra)
library(tidyverse, quietly=T)
library(forcats, quietly=T)
library(cowplot, quietly=T)    # publication-ready theme for ggplot2
library(scales, quietly=T)
```


```{r all_data, echo=FALSE}
load(file = here("data", "all_data.rda"))

n_md <- nlevels(all_data$md_desc)
n_papers = nrow(all_data)

assessment_type <- c("NO ASSESSMENT", "USABILITY/UX", "EFFECT AND USABILITY/UX", "EFFECT")
assessment_type_n <- sapply(assessment_type, FUN = function(x) {nrow(filter(all_data, val_type == x))})

n_assessment_no <- assessment_type_n[[1]]
n_assessment_yes <- n_papers - n_assessment_no 

# Keep the same order of mental disorder for all charts 
temp_for_order <- 
    all_data %>% 
    group_by(md_id, md_desc) %>%
    summarise(number_cases = n()) %>%
    mutate(proportion = number_cases/n_papers) %>% 
    arrange(desc(proportion), md_id) 

# convert to factor to retain sorted order of mental disorders 
temp_for_order$md_desc <- factor(temp_for_order$md_desc, levels=unique(temp_for_order$md_desc))  

# Save ordered mental disorders
md_all_ordered <- levels(temp_for_order$md_desc)


# Adjust labels length for figures production, based on the order of MD given in 'md_all_ordered'
md_lbl_production <- c(
  "Depressive disorders", 
  "Various disorders",
  "Anxiety disorders",
  "Substance-related and\n addictive disorders",
  "Schizophrenia spectrum and\n other psychotic disorders",
  "Trauma and\n stressor-related disorders",
  "Suicidal behavior disorder/\nnonsuicidal self-injury",
  "Comorbid disorders",
  "Bipolar and related disorders",
  "Obsessive-compulsive and\n related disorders",
  "Neurodevelopmental disorders",
  "Feeding and eating disorders",
  "Sleep-wake disorders",
  "Personality disorders",
  "Major and mild\n neurocognitive disorders")    


default_palette <- c("NO ASSESSMENT"="#AF8DC3", "USABILITY/UX"="#D9F0D3", "EFFECT AND USABILITY/UX"="#7FBF7B", "EFFECT"="#1B7837")
```



### Figure 3. Distribution of articles per mental disorder, categorized according to assessment type. 

```{r fig3_barchart, echo=FALSE, fig.width=10,fig.asp=0.65}
cols <- c("md", "md_id", "md_desc", "val_type")

data_plot_barchart <- 
    all_data %>%
    select(cols)

data_plot_barchart <- 
    data_plot_barchart %>% 
        group_by(md_id, md_desc, val_type) %>%  # first create counts for each group
        summarise(number_cases = n()) %>%
        mutate(proportion = number_cases/n_papers) %>% 
        ungroup() %>%
        group_by(md_id) %>%
        mutate(total_cases = sum(number_cases),
               proportion_sum = sum(proportion),
               proportion_lbl = paste0(round(proportion_sum*100,1), "%")) %>% 
        ungroup() %>%
        mutate(lbl = paste0(round(number_cases/total_cases*100,1), "%")) %>% 
        arrange(desc(proportion_sum), md_id)

# To keep "unified" order in plot.
data_plot_barchart$md_desc <- forcats::fct_relevel(data_plot_barchart$md_desc, md_all_ordered)  
data_plot_barchart$val_type <- forcats::fct_relevel(data_plot_barchart$val_type, assessment_type)

pal <- default_palette

lbls <- distinct(data_plot_barchart, md_desc, proportion_sum, proportion_lbl)

top_proportion <- sum(lbls[1:6, "proportion_sum"]) 
top_lbl <- paste0(round(top_proportion*100,1), "%")


```

### Breakdown of assessment types per mental disorder

```{r stats_assesstype_md, echo=FALSE}

# Table output with DT
data_plot_barchart %>%
  select(`Mental Disorder` = md_desc,
           `Type of assessment` = val_type,
           `Relative N` = number_cases,
           `Relative %`= lbl) %>%
  datatable(rownames = FALSE, 
            filter = "top",
            class = "table-bordered table-condensed hover",
            extensions = c("Buttons", "RowGroup"),
            options = list(
               pageLength = 8, #autoWidth = TRUE,
               dom = 'Bfrtip',  # https://datatables.net/reference/option/dom
               buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
               rowGroup=list(dataSrc=0)
            )) %>%
    formatStyle('Relative N',
      background = styleColorBar(c(0, data_plot_barchart$number_cases), 'lightblue'),
      backgroundSize = '98% 55%',
      backgroundRepeat = 'no-repeat',
      backgroundPosition = 'center')

```

### All papers
```{r tab_apps, echo=FALSE}
# data_all_apps <- 
#   all_data %>%
#   select(app_name, md_desc, year, id, fmw_cbt, fmw_wav, fmw_pos, fmw_tra, ux_gui, ux_gesture, ux_voice, ux_text) %>%
#   filter(!is.na(app_name)) %>%
#   arrange(md_desc, year)
# 
# 
# # a custom table container
# sketch <- 
#   htmltools::withTags(table(
#   class = 'display',
#   thead(
#     tr(
#       th(rowspan = 2, 'APP NAME'),
#       th(rowspan = 2, 'MD CATEGORY'),
#       th(rowspan = 2, 'YEAR'),
#       th(rowspan = 2, 'REF'),
#       th(colspan = 4, 'PSY FRAMEWORK'),
#       th(colspan = 3, 'UX')
#     ),
#     tr(
#       lapply(c('CBT', 'WAV', 'TRA', 'POS'), th),
#       lapply(c('GES', 'VOI', 'TXT'), th)
#     )
#   )
# ))
# 
# # sketch
# 
# data_all_apps %>%
#   select(`APP NAME` = app_name,
#          `MD CATEGORY` = md_desc,
#          `YEAR` = year,
#          `REF`= id,
#          `CBT` = fmw_cbt,
#          `WAV` = fmw_wav,
#          `TRA` = fmw_tra,
#          `POS` = fmw_pos,
#          `GES` = ux_gesture,
#          `VOI` = ux_voice,
#          `TXT` = ux_text) %>%
#   datatable(container = sketch, rownames = FALSE, 
#             filter = "top",
#             class = "table-bordered table-condensed hover",
#             extensions = "Buttons",
#             options = list(
#                pageLength = 6, #autoWidth = TRUE,
#                dom = 'Bfrtip',  # https://datatables.net/reference/option/dom
#                buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
#             )) %>%
#     formatStyle('CBT',
#       backgroundColor = styleEqual(c("YES", "NO"), c('red', ''))) %>%
#     formatStyle('WAV',
#       backgroundColor = styleEqual(c("YES", "NO"), c('orange', ''))) %>%
#     formatStyle('TRA',
#       backgroundColor = styleEqual(c("YES", "NO"), c('yellow', ''))) %>%
#     formatStyle('POS',
#       backgroundColor = styleEqual(c("YES", "NO"), c('blue', ''))) %>%
#     # formatStyle('GUI',
#     #   backgroundColor = styleEqual(c("YES", "NO"), c('lightgreen', ''))) %>%
#     formatStyle('GES',
#       backgroundColor = styleEqual(c("YES", "NO"), c('lightgreen', ''))) %>%
#     formatStyle('VOI',
#       backgroundColor = styleEqual(c("YES", "NO"), c('lightgreen', ''))) %>%
#     formatStyle('TXT',
#       backgroundColor = styleEqual(c("YES", "NO"), c('lightgreen', '')))
```  

